config/routes.rb
Idealme::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  get "pictures" => "ckeditor/pictures#index"
  post "pictures" => "ckeditor/pictures#create"

  get "screenshots/index" unless Rails.env.production?
  get "screenshots/reset" unless Rails.env.production?

  get "payload/:id/download" => "payload#download", as: :download_payload

  get "/ic/article/:slug" => "users#drip_content_article", as: :drip_content_article

  root to: 'landings#index'
  get 'ideal-life' => 'landings#index'
  get 'ideallife' => 'landings#hit_your_goals'
  get '__ping' => 'landings#ping'
  get 'aweber_callback' => 'landings#aweber_callback'
  get 'workbook' => 'landings#workbook'
  get 'hit-your-goals' => 'landings#hit_your_goals'
  get 'action-sidekick' => 'landings#action_sidekick'
  get 'continuity-offer-1' => 'landings#continuity_offer_1'
  get 'continuity-offer-2' => 'landings#continuity_offer_2'

  get 'thanks/:thanks_type' => 'landings#thanks'
  post 'purchase-continuity-offer' => 'landings#purchase_continuity_offer', as: :purchase_continuity_offer
  post 'purchase-action-sidekick' => 'landings#purchase_action_sidekick', as: :purchase_action_sidekick

  get 'download-workbook' => 'resources#download_workbook'

  get "now/:slug(/:market_tag)" => "affiliate_links#perform", slug: /[^\/]+/, as: :affiliate_link

  resources :searches, only: [:index]
  resources :lectures, only: [:index, :show]
  resources :feedbacks, only: [:index, :new, :create]
  resources :orders, only: [:new, :create] do
    collection do
      get 'new/action-sidekick' => 'orders#new_action_sidekick', as: :order_action_sidekick
      get 'new/workbook' => 'orders#new_workbook', as: :order_workbook
      get 'new/subscription' => 'orders#new_subscription', as: :order_subscription
      post 'create/workbook-order' => 'orders#create_workbook_order', as: :create_workbook_order
      post 'create/subscription-order' => 'orders#create_subscription_order', as: :create_subscription_order
      post 'create/action-sidekick-order' => 'orders#create_action_sidekick_order', as: :create_action_sidekick_order
      get 'new/:id' => 'orders#new', as: :subscribe
    end
  end

  resources :markets, only: [:index, :show] do
    collection do
      get ':market_affiliate_tag/:user_affiliate_tag/:tracking_affiliate_tag' => 'markets#affiliate_init', as: :markets_affiliate_tracking, user_affiliate_tag: /[^\/]+/
      get ':market_affiliate_tag/:user_affiliate_tag' => 'markets#affiliate_init', as: :markets_affiliate, user_affiliate_tag: /[^\/]+/
    end
  end

  resources :courses, only: [:index, :show] do
    resources :reviews
  end
  resources :discovers, only: [:index, :show]
  resources :resources do
    collection do
      get "my-goals" => :my_goals, as: :my_goals
      get "goal/:goal_id" => :goal, as: :goal
    end
  end
  resources :goals, only: [:index, :show] do
    resources :gems, controller: :jewels do
      member do
        put "" => 'jewels#update'
        get :comments
        get :modal_content
        post :save
      end
    end
    member do
      get ':tab' => 'goals#show', constraints: {tab: /(activity)|(top-gem)|(my-gem)|(course)/}, as: :tab
      post :share
      post :checkin
      post :activate
      post :complete
      post :archive
      post :toggle
      get 'filter/:filter_name' => 'goals#filter', as: :filter
    end
    collection do
      get :archived
      post '' => 'goals#choose'
    end
  end

  namespace :admin do
    root to: 'landings#index'
    resources :gems
    resources :markets do
      resources :payloads
    end
    resources :lectures do
      get 'payloads_partial' => 'lectures#payloads_partial'
      post 'attach_payload' => 'lectures#attach_payload'
      resources :payloads do
        member do
          put :remove
        end
      end
      collection do
        post :sort
      end
    end
    resources :articles do
      resources :payloads
    end

    resources :fragments

    resources :courses do
      member do
        post :sort_sections
        post :update
      end
    end
    resources :sections do
      collection do
        post :sort
      end
    end
    constraints(id: /[^\/]+/) do
      resources :users
      get 'users/:id/edit' => "users#edit", id: /[^\/]+/
    end
    resources :orders
    resources :goals
    resources :categories
    resources :polls
    resources :feedbacks
  end

  namespace :dashboard do
    root :to => 'landings#index'
    resources :swipes, :only => [:index, :show]
    resources :affiliates
    resources :redirections
    resources :payments
    resources :courses do
      resources :upsells
      member do
        post 'add_student'
      end
    end
  end


  namespace :ajax do
    resources :comments, only: [:create, :update, :destroy], defaults: {format: :json}
    constraints(id: /[0-9A-Za-z\-\.\_]+/) do
      resources :users, only: [:update], defaults: {format: :json}
    end
    resources :goals, only: [:index], defaults: {format: :json}
    resources :categories, only: [:index], defaults: {format: :json}
    resources :checkins, only: [:index, :show], defaults: {format: :json} do
      collection do
        get 'add_checkin' => 'checkins#add_checkin'
      end
    end
    resources :goal_users, only: [], defaults: {format: :json} do
      collection do
        post 'set_privacy' => 'goal_users#set_privacy'
        post 'set_order' => 'goal_users#set_order'
        post 'toggle_goal' => 'goal_users#toggle_goal'
      end
    end
    resources :votes, only: [], defaults: {format: :json} do
      collection do
        post 'up_vote' => 'votes#up_vote'
        post 'down_vote' => 'votes#down_vote'
        post 'un_vote' => 'votes#un_vote'
      end
    end
    resources :poll_results, only: [:create, :destroy], defaults: {format: :json}
    resources :poll_questions, only: [:show], defaults: {format: :json}
  end


  namespace :webhook do
    post 'sendgrid/notify' => 'send_grid#notify'
    post 'stripe/notify' => 'stripe#notify'
    resources :paypals, only: [] do
      collection do
        post 'paypal_return' => 'paypals#paypal_return'
        post 'paypal_cancel' => 'paypals#paypal_cancel'
        post 'paypal_create' => 'paypals#paypal_create'

        get 'paypal_return' => 'paypals#paypal_return'
        get 'paypal_cancel' => 'paypals#paypal_cancel'
      end
    end
  end

  as :user do
    patch '/users/confirmation' => 'users/confirmations#update', :via => :patch, :as => :update_user_confirmation
  end

  devise_for :users,
    path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      password: 'forgot_password',
      confirmation: 'verification',
      unlock: 'unblock',
      registration: 'register',
      sign_up: 'sign_up'},
      controllers: {
        omniauth_callbacks: 'users/omniauth_callbacks',
        confirmations: 'users/confirmations',
        passwords: 'users/passwords',
        registrations: 'users/registrations',
        sessions: 'users/sessions',
        unlocks: 'users/unlocks',
        invitations: 'users/invitations'}
      devise_scope :user do
        get 'users/auth/:provider' => 'users/omniauth_callbacks#passthru'
        get 'register/affiliate_sign_up' => 'users/registrations#new_affiliate', as: :new_affiliate_registration
        post 'register/affiliate_sign_up' => 'users/registrations#create_affiliate', as: :affiliate_registration
        constraints(id: /[0-9A-Za-z\-\.\_]+/) do
          get ':id' => 'users#profile', as: :user
          get 'user/sidekick' => 'users#sidekick', as: :sidekick

          get ':id/sdfsdf/:tab' => 'users#profile', constraints: {tab: /(goal)|(course)|(saved-course)/}, as: :user_tab

          get ':id/edit' => 'users/registrations#edit', as: :user_edit
          get ':id/edit_password' => 'users/registrations#edit_password', as: :user_edit_password

          # Signup flow
          #get ':id/welcome' => 'users#welcome', as: :user_welcome
          get 'user/welcome' => 'users#welcome', as: :user_welcome
          post 'user/welcome' => 'users#welcome_save'
          post 'user/dismiss-welcome-message' => 'users#dismiss_welcome_message'
          # Signup flow


          get ':id/friend' => 'users#friend', as: :user_friend
          get ':id/stuff' => 'users#stuff', as: :user_stuff
          get ':id/feed' => 'users#feed', as: :user_feed
          get ':id/notification' => 'users#notification', as: :user_notification
          get ':id/identity' => 'users#identity', as: :user_identity
          get ':id/identity/:pid/revoke' => 'users#identity_revoke', as: :user_identity_revoke
        end
      end
      comfy_route :cms_admin, :path => '/admin/cms'
      comfy_route :cms, :path => '/static', :sitemap => false
end

app/controllers/jewels_controller.rb
class JewelsController < ApplicationController
  before_filter :load_goal
  def index
    @jewels = @goal.jewels.where(visible: true)
  end

  def show
    @jewel = Jewel.find(params[:id])
    respond_to do |format|
      format.json do
        render json: {
          name: @jewel.name,
          truncated_name: @jewel.name.truncate(50),
          image: @jewel.avatar.url(:bigger),
          link: @jewel.url,
          truncated_link: @jewel.url.truncate(50),
          comments_path: comments_goal_gem_path(@jewel.linked_goal, @jewel),
        }
      end
      format.html do
        # redirect_to goal_path(@jewel.linked_goal, gem: @jewel.slug)
        if current_user
          @goal_user = GoalUser.find_or_initialize_by(user: current_user, goal: @jewel.linked_goal)
        else
          @goal_user = GoalUser.find_or_initialize_by(goal: @jewel.linked_goal)
        end

        @goal = @goal_user.goal
        @jewels = @goal.jewels.filter(:all)
        @open_gem = goal_gem_path(@jewel.linked_goal, @jewel)
        render 'goals/show'
      end
    end
  end

  def save
    @jewel = Jewel.find(params[:id])
    if SavedJewel.where(jewel: @jewel, user: current_user).exists?
      SavedJewel.where(jewel: @jewel, user: current_user).destroy_all
      render json: { status: :destroyed }
    else
      SavedJewel.create(jewel: @jewel, user: current_user)
      render json: { status: :created }
    end
  end

  def comments
    @jewel = Jewel.find(params[:id])
    render layout: nil
  end

  def modal_content
    @filter_name = params[:filter]
    jewels = @goal.jewels.filter(params[:filter]).to_a
    ref = jewels.find { |jewel| jewel.slug == params[:id] }
    if params[:rel] == 'next'
      @jewel = jewels.fetch(jewels.index(ref) + 1, nil)
    elsif params[:rel] == 'prev'
      @jewel = jewels.fetch(jewels.index(ref) - 1, nil)
    else
      @jewel = Jewel.find(params[:id])
    end
    if @jewel.nil?
      if params[:rel] == 'next'
        @jewel = jewels.first
      elsif params[:rel] == 'prev'
        @jewel = jewels.last
      else
        @jewel = Jewel.find(params[:id])
      end

    end
    render layout: nil
  end

  def create
    url = params.require(:url)
    jewel = Jewel.mine(current_user, url, @goal)
    render json: {
      url: jewel.url,
      truncated_url: jewel.url.truncate(50),
      image: jewel.avatar.url(:bigger),
      title: jewel.name,
      truncated_title: jewel.name.try(:truncate, 50),
      edit_path: goal_gem_path(@goal, jewel),
      comments_path: comments_goal_gem_path(@goal, jewel),
      embed_content: jewel.embed_content,
      kind: Jewel::TYPES.invert[jewel.kind]
    }
  rescue ActionController::ParameterMissing => e
    render json: { error: 'Missing url' }, status: 500
  rescue DuplicateJewel => e
    render json: { error: 'Duplicate gem', jewel_link: goal_gem_path(e.jewel.linked_goal, e.jewel) }, status: 500
  end

  def update
    unless params['gemType'].present?
      render json: { success: false, error: 'Gem type is missing' }
      return
    end
    unless params['title'].present?
      render json: { success: false, error: 'Gem title is missing' }
      return
    end
    jewel = Jewel.where(owner: current_user, slug: params[:id]).first
    jewel.name = params['title']

    jewel.kind = Jewel::TYPES[params['gemType']]
    jewel.visible = true
    jewel.slug = nil
    jewel.save!

    # add comment to jewel if present
    comment_content = params['gemComment']
    unless comment_content.blank?
      comment = jewel.comments.build(owner: current_user, content: comment_content)
      comment.save!
    end
    render json: { success: true }
  end

  protected

  def load_goal
    @goal = Goal.find params[:goal_id]
  end
end

app/helpers/jewels_helper.rb
module JewelsHelper
  def filter_link(label, filter_name)
    link_class = ''
    link_class = 'active' if params[:filter_name] == filter_name.to_s
    if link_class == 'active'
      content_tag :span, label, class: link_class
    else
      link_to label, filter_goal_path(filter_name: filter_name), class: link_class
    end
  end
end

app/views/jewels/_comments.html.slim
.jewel-comments
  - @jewel.comments.each do |comment|
    .jewel-comment
      .row
        .thumb = image_tag comment.owner.avatar.url(:thumb)
        .comment-content 
          p.pull-right = abbreviated_time_ago comment.created_at
          p = comment.owner.fullname
          p = comment.content
          .boxes.vote-controls data-id=comment.id data-type=comment.class
            .box
              .icon-btn.upvote-icon-btn.like data-voted=upvoted?(comment, current_user)
                i.icon-thumbs-up
                span.vote-count.upvote-total = comment.up_votes
            .box
              .icon-btn.downvote-icon-btn.dislike data-voted=downvoted?(comment, current_user)
                i.icon-thumbs-down
                span.vote-count.downvote-total = comment.down_votes
  - if current_user
    .jewel-comment
      .row
        .thumb = image_tag current_user.avatar(:thumb), class: 'user-avatar'
        .comment-content
          p Why this is awesome:
          input#gem-comment type="text" name="gem-comment"

app/views/jewels/_jewel.html.slim
.gem-card
  = link_to modal_content_goal_gem_path(jewel.linked_goal, jewel, filter: @filter_name), :class => 'view-gem-link', 'data-jewel-id' => jewel.slug do
    .avatar
      - if jewel.avatar.present?
        = image_tag jewel.avatar.url(:full)
      - else
        img src="/missing/no-gem-link.jpg" 
  .gem-name
    = jewel.name.truncate(30)
  .bottom-box
    .picker
      = render partial: "jewels/vote_buttons", locals: { jewel: jewel }

app/views/jewels/_vote_buttons.html.slim
.boxes.vote-controls data-id=jewel.id data-type=jewel.class
  .box
    .icon-btn.upvote-icon-btn.like data-voted=upvoted?(jewel, current_user)
      i.icon-thumbs-up
      span.vote-count.upvote-total = jewel.up_votes
  .box.br
    .icon-btn.downvote-icon-btn.dislike data-voted=downvoted?(jewel, current_user)
      i.icon-thumbs-down
      span.vote-count.downvote-total = jewel.down_votes
  = link_to modal_content_goal_gem_path(jewel.linked_goal, jewel), :class => 'view-gem-link', 'data-jewel-id' => jewel.slug do
    .box.br
      .icon-btn
        i.icon-comment-alt
        span.comment-count = jewel.comments.count
  a.box.save-link href=save_goal_gem_path(goal_id: jewel.goal_id, id: jewel.slug)
    - if current_user && jewel.saved_by(current_user)
      .icon-btn.unsave-link-icon: i.icon-ok
      .icon-btn.save-link-icon.hidden: i.icon-plus
    - else
      .icon-btn.unsave-link-icon.hidden: i.icon-ok
      .icon-btn.save-link-icon: i.icon-plus

app/views/jewels/comments.html.slim
= render partial: "jewels/comments"

app/views/jewels/index.html.slim
.container
  .gem-header.clearfix
    .col-sm-4
      = image_tag @goal.avatar.url(:thumb)
      | &nbsp;
      span.goal-name = @goal.name
    .col-sm-4: .center-block: center
      span 2
    .col-sm-4: .pull-right
      i Find something great?
      | &nbsp;
      a.btn.btn-red.btn-new-gem
        i.glyphicon.glyphicon-cloud-upload
        | &nbsp;
        ' submit gem
        
  .gem-grid.row
    = render partial: "jewel", collection: @jewels



.new-gem-modal.modal.fade: .modal-dialog: .modal-content
  .modal-header
    button.close aria-hidden="true" &times;
    h4.modal-title Add a new gem!
  .modal-body: .row
    .col-sm-8
      input.form-control.add-gem-url-input type="text" placeholder="enter a URL" value="http://shop.lululemon.com/products/clothes-accessories/pants-yoga/Wunder-Under-Pant-Reversible-31552?cc=12457&skuId=3528843&catId=pants-yoga"
    .col-sm-4.gem-submit-btn-container
      button.btn.btn-primary.btn-post-gem GO
  .modal-footer
    p You can add any web page, article, image, video, Tweet or Facebook post that has heped you with the weight loss goal 

.edit-gem-modal.modal.fade: .modal-dialog: .modal-content
  .modal-header
    button.close aria-hidden="true" &times;
    .not-editing-title
      .row
        .col-sm-10
          h4.modal-gem-title
          i.glyphicon.glyphicon-edit
        .col-sm-2: i.glyphicon.glyphicon-edit
    .editing-title
      input#gem-title-input.hide type="text" name="gem-title"
  .modal-body
    .row: .col-sm-12
      ' This is a 
      input type="radio" name="gem-type" value="course" 
      '  Course
      input type="radio" name="gem-type" value="article" 
      '  Article
      input type="radio" name="gem-type" value="video" 
      '  Video
      input type="radio" name="gem-type" value="product" 
      '  Product
    .row: .col-sm-12
      center: img.gem-image
    .row: .col-sm-12
      p
        a.gem-link
    .row
      .col-sm-1
        = image_tag current_user.avatar(:thumb), class: 'user-avatar'
      .col-sm-11
        p
          ' blah blah blah
    .row: .col-sm-12
      button.btn.btn-primary.btn-edit-gem CREATE GEM

app/views/jewels/modal_content.html.slim
.modal-header data-href=modal_content_goal_gem_path(@jewel.linked_goal, @jewel, filter: @filter_name)
  button.close aria-hidden="true" &times;
  h4.modal-title = @jewel.name.truncate(50)
  .gem-submitter-and-vote-controls
  .boxes.vote-controls data-id=@jewel.id data-type=@jewel.class
    .box.btn.btn-default
      a href="#{save_goal_gem_path(@jewel.linked_goal, @jewel)}": .icon-btn.save-link
        - if current_user && @jewel.saved_by(current_user)
          i.icon.icon-plus.hidden
          i.icon.icon-ok
        - else
          i.icon.icon-plus
          i.icon.icon-ok.hidden
    .box.btn.btn-default
      .icon-btn.upvote-icon-btn.like data-voted=upvoted?(@jewel, current_user)
        i.icon-thumbs-up
        span.vote-count.upvote-total = @jewel.up_votes
    .box.btn.btn-default
      .icon-btn.downvote-icon-btn.dislike data-voted=downvoted?(@jewel, current_user)
        i.icon-thumbs-down
        span.vote-count.downvote-total = @jewel.down_votes
    span.submitter #{@jewel.owner.fullname} shared this | 1 of 123 gems
  br
    span.gem-count.pull-left
.modal-body: .row
  .col-sm-6.gem-image-container
    - if @jewel.embed_content.present?
      center: .gem-embed == @jewel.embed_content
    - else
      center: a.gem-link target="_blank": img.gem-image src=@jewel.avatar.url(:bigger)

  .col-sm-6
    .gem-comments
      = render partial: "comments"
  .row